/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-13 10:23:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>About</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 	<section class=\"bg-img1 txt-center p-lr-15 p-tb-92\"\r\n");
      out.write("		style=\"background-image: url(/shopbangiay-jsp-servlet/Images/Shoe image/Nike InfinityRN 4/Green white/green_white_8.png);\">\r\n");
      out.write("		<h2 class=\"ltext-105 cl0 txt-center\">About</h2>\r\n");
      out.write("	</section>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Content page -->\r\n");
      out.write("	<section class=\"bg0 p-t-75 p-b-120\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row p-b-148\">\r\n");
      out.write("				<div class=\"col-md-7 col-lg-8\">\r\n");
      out.write("					<div class=\"p-t-7 p-r-85 p-r-15-lg p-r-0-md\">\r\n");
      out.write("						<h3 class=\"mtext-111 cl2 p-b-16\">Our Story</h3>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">Hành trình của chúng tôi bắt\r\n");
      out.write("							đầu với một niềm đam mê cháy bỏng với giày dép và sự mong muốn\r\n");
      out.write("							chia sẻ niềm đam mê đó với mọi người. Nơi mà mọi bước chân đều là\r\n");
      out.write("							một câu chuyện, một tấm lòng. Chúng tôi mở cửa hàng giày với mục\r\n");
      out.write("							tiêu không chỉ là nơi để mua sắm, mà còn là nơi để trải nghiệm và\r\n");
      out.write("							chia sẻ những câu chuyện.</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">Với mỗi đôi giày được chọn lựa\r\n");
      out.write("							kỹ càng, chúng tôi muốn tạo ra một trải nghiệm mua sắm đầy ấn\r\n");
      out.write("							tượng và độc đáo. Mỗi chiếc giày không chỉ là một sản phẩm, mà\r\n");
      out.write("							còn là một phần của cuộc sống, là một biểu tượng của phong cách\r\n");
      out.write("							và cá tính.</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">Từ những đôi giày thoải mái\r\n");
      out.write("							dành cho ngày dạo phố đến những đôi giày lịch lãm dành cho buổi\r\n");
      out.write("							tiệc tối, chúng tôi tự hào mang đến cho khách hàng một sự đa dạng\r\n");
      out.write("							với các thương hiệu hàng đầu và các mẫu mã phong phú.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-11 col-md-5 col-lg-4 m-lr-auto\">\r\n");
      out.write("					<div class=\"how-bor1 \">\r\n");
      out.write("						<div class=\"hov-img0\">\r\n");
      out.write("							<img src=\"/shopbangiay-jsp-servlet/Images/Shoe image/Nike Air Max Plus/air-max-plus-shoes-4.png\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"order-md-2 col-md-7 col-lg-8 p-b-30\">\r\n");
      out.write("					<div class=\"p-t-7 p-l-85 p-l-15-lg p-l-0-md\">\r\n");
      out.write("						<h3 class=\"mtext-111 cl2 p-b-16\">Our Mission</h3>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">Nhiệm vụ của chúng tôi không\r\n");
      out.write("							chỉ là bán giày, mà còn là tạo ra một cộng đồng đam mê và sự kết\r\n");
      out.write("							nối thông qua niềm đam mê chung về giày dép. Chúng tôi cam kết\r\n");
      out.write("							mang đến cho khách hàng trải nghiệm mua sắm độc đáo và không thể\r\n");
      out.write("							nào quên, kết hợp với dịch vụ chăm sóc khách hàng tận tình và chu\r\n");
      out.write("							đáo. Chúng tôi đặt ra một số mục tiêu cụ thể:</p>\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">1. Đa dạng sản phẩm: Chúng tôi\r\n");
      out.write("							luôn cập nhật và mang đến cho khách hàng một loạt các sản phẩm từ\r\n");
      out.write("							các thương hiệu uy tín và các xu hướng mới nhất trong ngành giày\r\n");
      out.write("							dép.</p>\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">2. Chất lượng hàng đầu: Chúng\r\n");
      out.write("							tôi chọn lựa kỹ lưỡng từng sản phẩm để đảm bảo chất lượng và sự\r\n");
      out.write("							thoải mái cho người sử dụng.</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">3. Trải nghiệm mua sắm độc\r\n");
      out.write("							đáo: Chúng tôi tạo ra không gian mua sắm thân thiện và ấm cúng,\r\n");
      out.write("							nơi mà khách hàng có thể thảo luận, chia sẻ và tìm kiếm những đôi\r\n");
      out.write("							giày phản ánh phong cách và cá tính của họ.</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">4. Tạo cộng đồng: Chúng tôi\r\n");
      out.write("							xây dựng một cộng đồng đam mê quanh chủ đề giày dép, nơi mọi\r\n");
      out.write("							người có thể kết nối, chia sẻ và học hỏi từ nhau.</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">5. Phục vụ khách hàng tận\r\n");
      out.write("							tình: Chúng tôi cam kết luôn lắng nghe và đáp ứng nhanh chóng mọi\r\n");
      out.write("							nhu cầu và yêu cầu của khách hàng, từ khi họ bước vào cửa hàng\r\n");
      out.write("							cho đến khi họ rời đi với một đôi giày ưng ý.</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">6. Đa dạng sản phẩm: Chúng tôi\r\n");
      out.write("							luôn cập nhật và mang đến cho khách hàng một loạt các sản phẩm từ\r\n");
      out.write("							các thương hiệu uy tín và các xu hướng mới nhất trong ngành giày\r\n");
      out.write("							dép.</p>\r\n");
      out.write("						<p class=\"stext-113 cl6 p-b-26\">Tất cả những nỗ lực của\r\n");
      out.write("							chúng tôi hướng đến một mục tiêu duy nhất: mang lại niềm vui và\r\n");
      out.write("							sự hài lòng tuyệt đối cho khách hàng trong mỗi trải nghiệm mua\r\n");
      out.write("							sắm tại cửa hàng của chúng tôi.</p>\r\n");
      out.write("						<div class=\"bor16 p-l-29 p-b-9 m-t-22\">\r\n");
      out.write("							<p class=\"stext-114 cl6 p-r-40 p-b-11\"></p>\r\n");
      out.write("	\r\n");
      out.write("							<span class=\"stext-111 cl8\"> - Trần Huỳnh Vũ </span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30\">\r\n");
      out.write("					<div class=\"how-bor2\">\r\n");
      out.write("						<div class=\"hov-img0\">\r\n");
      out.write("							<img src=\"/shopbangiay-jsp-servlet/Images/Shoe image/Nike InfinityRN 4/Green white/green_white_8.png\" alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
