/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-05 19:26:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Trang chu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Cart -->\r\n");
      out.write("	<div class=\"wrap-header-cart js-panel-cart\">\r\n");
      out.write("		<div class=\"s-full js-hide-cart\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"header-cart flex-col-l p-l-65 p-r-25\">\r\n");
      out.write("			<div class=\"header-cart-title flex-w flex-sb-m p-b-8\">\r\n");
      out.write("				<span class=\"mtext-103 cl2\"> Your Cart </span>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart\">\r\n");
      out.write("					<i class=\"zmdi zmdi-close\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-cart-content flex-w js-pscroll\">\r\n");
      out.write("				<ul class=\"header-cart-wrapitem w-full\">\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("								alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								White Shirt Pleat </a> <span class=\"header-cart-item-info\"> 1\r\n");
      out.write("								x $19.00 </span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("								alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								Converse All Star </a> <span class=\"header-cart-item-info\"> 1\r\n");
      out.write("								x $39.00 </span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"header-cart-item flex-w flex-t m-b-12\">\r\n");
      out.write("						<div class=\"header-cart-item-img\">\r\n");
      out.write("							<img src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("								alt=\"IMG\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"header-cart-item-txt p-t-8\">\r\n");
      out.write("							<a href=\"#\" class=\"header-cart-item-name m-b-18 hov-cl1 trans-04\">\r\n");
      out.write("								Nixon Porter Leather </a> <span class=\"header-cart-item-info\">\r\n");
      out.write("								1 x $17.00 </span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"w-full\">\r\n");
      out.write("					<div class=\"header-cart-total w-full p-tb-40\">Total: $75.00</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"header-cart-buttons flex-w w-full\">\r\n");
      out.write("						<a href=\"shoping-cart.html\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10\">\r\n");
      out.write("							View Cart </a> <a href=\"shoping-cart.html\"\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("							Check Out </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Slider -->\r\n");
      out.write("	<section class=\"section-slide\">\r\n");
      out.write("		<div class=\"wrap-slick1\">\r\n");
      out.write("			<div class=\"slick1\">\r\n");
      out.write("				<div class=\"item-slick1\"\r\n");
      out.write("					style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write(")\">\r\n");
      out.write("					<div class=\"container h-full\">\r\n");
      out.write("						<div class=\"flex-col-l-m h-full p-t-100 p-b-30 respon5\">\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"fadeInDown\" data-delay=\"0\">\r\n");
      out.write("								<span class=\"ltext-101 cl2 respon2\"> Women Collection\r\n");
      out.write("									2018 </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"fadeInUp\" data-delay=\"800\">\r\n");
      out.write("								<h2 class=\"ltext-201 cl2 p-t-19 p-b-43 respon1\">NEW SEASON\r\n");
      out.write("								</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"zoomIn\" data-delay=\"1600\">\r\n");
      out.write("								<a href=\"product.html\"\r\n");
      out.write("									class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("									Shop Now </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item-slick1\"\r\n");
      out.write("					style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("					<div class=\"container h-full\">\r\n");
      out.write("						<div class=\"flex-col-l-m h-full p-t-100 p-b-30 respon5\">\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rollIn\" data-delay=\"0\">\r\n");
      out.write("								<span class=\"ltext-101 cl2 respon2\"> Men New-Season </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"lightSpeedIn\" data-delay=\"800\">\r\n");
      out.write("								<h2 class=\"ltext-201 cl2 p-t-19 p-b-43 respon1\">Jackets &\r\n");
      out.write("									Coats</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"slideInUp\" data-delay=\"1600\">\r\n");
      out.write("								<a href=\"product.html\"\r\n");
      out.write("									class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("									Shop Now </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item-slick1\"\r\n");
      out.write("					style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("					<div class=\"container h-full\">\r\n");
      out.write("						<div class=\"flex-col-l-m h-full p-t-100 p-b-30 respon5\">\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rotateInDownLeft\" data-delay=\"0\">\r\n");
      out.write("								<span class=\"ltext-101 cl2 respon2\"> Men Collection 2018\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rotateInUpRight\" data-delay=\"800\">\r\n");
      out.write("								<h2 class=\"ltext-201 cl2 p-t-19 p-b-43 respon1\">New\r\n");
      out.write("									arrivals</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"layer-slick1 animated visible-false\"\r\n");
      out.write("								data-appear=\"rotateIn\" data-delay=\"1600\">\r\n");
      out.write("								<a href=\"product.html\"\r\n");
      out.write("									class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("									Shop Now </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Banner -->\r\n");
      out.write("	<div class=\"sec-banner bg0 p-t-80 p-b-50\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6 col-xl-4 p-b-30 m-lr-auto\">\r\n");
      out.write("					<!-- Block1 -->\r\n");
      out.write("					<div class=\"block1 wrap-pic-w\">\r\n");
      out.write("						<img src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("							alt=\"IMG-BANNER\"> <a href=\"product.html\"\r\n");
      out.write("							class=\"block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3\">\r\n");
      out.write("							<div class=\"block1-txt-child1 flex-col-l\">\r\n");
      out.write("								<span class=\"block1-name ltext-102 trans-04 p-b-8\"> Women\r\n");
      out.write("								</span> <span class=\"block1-info stext-102 trans-04\"> Spring\r\n");
      out.write("									2018 </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block1-txt-child2 p-b-4 trans-05\">\r\n");
      out.write("								<div class=\"block1-link stext-101 cl0 trans-09\">Shop Now</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-xl-4 p-b-30 m-lr-auto\">\r\n");
      out.write("					<!-- Block1 -->\r\n");
      out.write("					<div class=\"block1 wrap-pic-w\">\r\n");
      out.write("						<img src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("							alt=\"IMG-BANNER\"> <a href=\"product.html\"\r\n");
      out.write("							class=\"block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3\">\r\n");
      out.write("							<div class=\"block1-txt-child1 flex-col-l\">\r\n");
      out.write("								<span class=\"block1-name ltext-102 trans-04 p-b-8\"> Men </span>\r\n");
      out.write("\r\n");
      out.write("								<span class=\"block1-info stext-102 trans-04\"> Spring 2018\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block1-txt-child2 p-b-4 trans-05\">\r\n");
      out.write("								<div class=\"block1-link stext-101 cl0 trans-09\">Shop Now</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-xl-4 p-b-30 m-lr-auto\">\r\n");
      out.write("					<!-- Block1 -->\r\n");
      out.write("					<div class=\"block1 wrap-pic-w\">\r\n");
      out.write("						<img src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("							alt=\"IMG-BANNER\"> <a href=\"product.html\"\r\n");
      out.write("							class=\"block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3\">\r\n");
      out.write("							<div class=\"block1-txt-child1 flex-col-l\">\r\n");
      out.write("								<span class=\"block1-name ltext-102 trans-04 p-b-8\">\r\n");
      out.write("									Accessories </span> <span class=\"block1-info stext-102 trans-04\">\r\n");
      out.write("									New Trend </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block1-txt-child2 p-b-4 trans-05\">\r\n");
      out.write("								<div class=\"block1-link stext-101 cl0 trans-09\">Shop Now</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Product -->\r\n");
      out.write("	<section class=\"bg0 p-t-23 p-b-140\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"p-b-10\">\r\n");
      out.write("				<h3 class=\"ltext-103 cl5\">Product Overview</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"flex-w flex-sb-m p-b-52\">\r\n");
      out.write("				<div class=\"flex-w flex-l-m filter-tope-group m-tb-10\">\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1\"\r\n");
      out.write("						data-filter=\"*\">All Products</button>\r\n");
      out.write("\r\n");
      out.write("					<button class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5\"\r\n");
      out.write("						data-filter=\".women\">Women</button>\r\n");
      out.write("\r\n");
      out.write("					<button class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5\"\r\n");
      out.write("						data-filter=\".men\">Men</button>\r\n");
      out.write("\r\n");
      out.write("					<button class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5\"\r\n");
      out.write("						data-filter=\".bag\">Bag</button>\r\n");
      out.write("\r\n");
      out.write("					<button class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5\"\r\n");
      out.write("						data-filter=\".shoes\">Shoes</button>\r\n");
      out.write("\r\n");
      out.write("					<button class=\"stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5\"\r\n");
      out.write("						data-filter=\".watches\">Watches</button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"flex-w flex-c-m m-tb-10\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"flex-c-m stext-106 cl6 size-104 bor4 pointer hov-btn3 trans-04 m-r-8 m-tb-4 js-show-filter\">\r\n");
      out.write("						<i\r\n");
      out.write("							class=\"icon-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-filter-list\"></i>\r\n");
      out.write("						<i\r\n");
      out.write("							class=\"icon-close-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none\"></i>\r\n");
      out.write("						Filter\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search\">\r\n");
      out.write("						<i class=\"icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search\"></i>\r\n");
      out.write("						<i\r\n");
      out.write("							class=\"icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none\"></i>\r\n");
      out.write("						Search\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Search product -->\r\n");
      out.write("				<div class=\"dis-none panel-search w-full p-t-10 p-b-15\">\r\n");
      out.write("					<div class=\"bor8 dis-flex p-l-15\">\r\n");
      out.write("						<button class=\"size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04\">\r\n");
      out.write("							<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("\r\n");
      out.write("						<input class=\"mtext-107 cl2 size-114 plh2 p-r-15\" type=\"text\"\r\n");
      out.write("							name=\"search-product\" placeholder=\"Search\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Filter -->\r\n");
      out.write("				<div class=\"dis-none panel-filter w-full p-t-10\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm\">\r\n");
      out.write("						<div class=\"filter-col1 p-r-15 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Sort By</div>\r\n");
      out.write("\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Default </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Popularity </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Average rating </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04 filter-link-active\">\r\n");
      out.write("										Newness </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Price: Low to High\r\n");
      out.write("								</a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> Price: High to Low\r\n");
      out.write("								</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"filter-col2 p-r-15 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Price</div>\r\n");
      out.write("\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04 filter-link-active\">\r\n");
      out.write("										All </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $0.00 - $50.00 </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $50.00 - $100.00 </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $100.00 - $150.00 </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $150.00 - $200.00 </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04\"> $200.00+ </a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"filter-col3 p-r-15 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Color</div>\r\n");
      out.write("\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #222;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Black </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #4272d7;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\"\r\n");
      out.write("									class=\"filter-link stext-106 trans-04 filter-link-active\">\r\n");
      out.write("										Blue </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #b3b3b3;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Grey </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #00ad5f;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Green </a>\r\n");
      out.write("								</li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #fa4251;\"> <i class=\"zmdi zmdi-circle\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> Red </a></li>\r\n");
      out.write("\r\n");
      out.write("								<li class=\"p-b-6\"><span class=\"fs-15 lh-12 m-r-6\"\r\n");
      out.write("									style=\"color: #aaa;\"> <i class=\"zmdi zmdi-circle-o\"></i>\r\n");
      out.write("								</span> <a href=\"#\" class=\"filter-link stext-106 trans-04\"> White </a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"filter-col4 p-b-27\">\r\n");
      out.write("							<div class=\"mtext-102 cl2 p-b-15\">Tags</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"flex-w p-t-4 m-r--5\">\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Fashion </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Lifestyle </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Denim </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Streetstyle </a> <a href=\"#\"\r\n");
      out.write("									class=\"flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5\">\r\n");
      out.write("									Crafts </a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row isotope-grid\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<!-- Load more -->\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"flex-c-m flex-w w-full p-t-45\">\r\n");
      out.write("					<a href=\"#\"\r\n");
      out.write("						class=\"flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04\">\r\n");
      out.write("						Load More </a>\r\n");
      out.write("				</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal1 -->\r\n");
      out.write("	<div class=\"wrap-modal1 js-modal1 p-t-60 p-b-20 \">\r\n");
      out.write("		<div class=\"overlay-modal1 js-hide-modal1\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"bg0 p-t-60 p-b-30 p-lr-15-lg how-pos3-parent\">\r\n");
      out.write("				<button class=\"how-pos3 hov3 trans-04 js-hide-modal1\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"");
      if (_jspx_meth_c_005furl_005f13(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						alt=\"CLOSE\">\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 col-lg-7 p-b-30\">\r\n");
      out.write("						<div class=\"p-l-25 p-r-30 p-lr-0-lg\">\r\n");
      out.write("							<div class=\"wrap-slick3 flex-sb flex-w\">\r\n");
      out.write("								<div class=\"wrap-slick3-dots\"></div>\r\n");
      out.write("								<div class=\"wrap-slick3-arrows flex-sb-m flex-w\"></div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"slick3 gallery-lb\">\r\n");
      out.write("									<div class=\"item-slick3\"\r\n");
      out.write("										data-thumb=\"images/product-detail-01.jpg'/>\">\r\n");
      out.write("										<div class=\"wrap-pic-w pos-relative\">\r\n");
      out.write("											<img\r\n");
      out.write("												src=\"");
      if (_jspx_meth_c_005furl_005f14(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("												alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("												class=\"flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04\"\r\n");
      out.write("												href=\"images/product-detail-01.jpg'/>\"> <i\r\n");
      out.write("												class=\"fa fa-expand\"></i>\r\n");
      out.write("											</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"item-slick3\"\r\n");
      out.write("										data-thumb=\"images/product-detail-02.jpg'/>\">\r\n");
      out.write("										<div class=\"wrap-pic-w pos-relative\">\r\n");
      out.write("											<img\r\n");
      out.write("												src=\"");
      if (_jspx_meth_c_005furl_005f15(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("												alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("												class=\"flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04\"\r\n");
      out.write("												href=\"images/product-detail-02.jpg'/>\"> <i\r\n");
      out.write("												class=\"fa fa-expand\"></i>\r\n");
      out.write("											</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"item-slick3\"\r\n");
      out.write("										data-thumb=\"images/product-detail-03.jpg'/>\">\r\n");
      out.write("										<div class=\"wrap-pic-w pos-relative\">\r\n");
      out.write("											<img\r\n");
      out.write("												src=\"");
      if (_jspx_meth_c_005furl_005f16(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("												alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("												class=\"flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04\"\r\n");
      out.write("												href=\"images/product-detail-03.jpg'/>\"> <i\r\n");
      out.write("												class=\"fa fa-expand\"></i>\r\n");
      out.write("											</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-md-6 col-lg-5 p-b-30\">\r\n");
      out.write("						<div class=\"p-r-50 p-t-5 p-lr-0-lg\">\r\n");
      out.write("							<h4 class=\"mtext-105 cl2 js-name-detail p-b-14\">Lightweight\r\n");
      out.write("								Jacket</h4>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"mtext-106 cl2\"> $58.79 </span>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"stext-102 cl3 p-t-23\">Nulla eget sem vitae eros\r\n");
      out.write("								pharetra viverra. Nam vitae luctus ligula. Mauris consequat\r\n");
      out.write("								ornare feugiat.</p>\r\n");
      out.write("\r\n");
      out.write("							<!--  -->\r\n");
      out.write("							<div class=\"p-t-33\">\r\n");
      out.write("								<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("									<div class=\"size-203 flex-c-m respon6\">Size</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"size-204 respon6-next\">\r\n");
      out.write("										<div class=\"rs1-select2 bor8 bg0\">\r\n");
      out.write("											<select class=\"js-select2\" name=\"time\">\r\n");
      out.write("												<option>Choose an option</option>\r\n");
      out.write("												<option>Size S</option>\r\n");
      out.write("												<option>Size M</option>\r\n");
      out.write("												<option>Size L</option>\r\n");
      out.write("												<option>Size XL</option>\r\n");
      out.write("											</select>\r\n");
      out.write("											<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("									<div class=\"size-203 flex-c-m respon6\">Color</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"size-204 respon6-next\">\r\n");
      out.write("										<div class=\"rs1-select2 bor8 bg0\">\r\n");
      out.write("											<select class=\"js-select2\" name=\"time\">\r\n");
      out.write("												<option>Choose an option</option>\r\n");
      out.write("												<option>Red</option>\r\n");
      out.write("												<option>Blue</option>\r\n");
      out.write("												<option>White</option>\r\n");
      out.write("												<option>Grey</option>\r\n");
      out.write("											</select>\r\n");
      out.write("											<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("									<div class=\"size-204 flex-w flex-m respon6-next\">\r\n");
      out.write("										<div class=\"wrap-num-product flex-w m-r-20 m-tb-10\">\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m\">\r\n");
      out.write("												<i class=\"fs-16 zmdi zmdi-minus\"></i>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<input class=\"mtext-104 cl3 txt-center num-product\"\r\n");
      out.write("												type=\"number\" name=\"num-product\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m\">\r\n");
      out.write("												<i class=\"fs-16 zmdi zmdi-plus\"></i>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<button\r\n");
      out.write("											class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail\">\r\n");
      out.write("											Add to cart</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!--  -->\r\n");
      out.write("							<div class=\"flex-w flex-m p-l-100 p-t-40 respon7\">\r\n");
      out.write("								<div class=\"flex-m bor9 p-r-10 m-r-11\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100\"\r\n");
      out.write("										data-tooltip=\"Add to Wishlist\"> <i\r\n");
      out.write("										class=\"zmdi zmdi-favorite\"></i>\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("									data-tooltip=\"Facebook\"> <i class=\"fa fa-facebook\"></i>\r\n");
      out.write("								</a> <a href=\"#\"\r\n");
      out.write("									class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("									data-tooltip=\"Twitter\"> <i class=\"fa fa-twitter\"></i>\r\n");
      out.write("								</a> <a href=\"#\"\r\n");
      out.write("									class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("									data-tooltip=\"Google Plus\"> <i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 	<script type=\"text/javascript\">\r\n");
      out.write("	    $(\".js-show-modal1\").click(function() {\r\n");
      out.write("	        var idShoe = $(this).data(\"idshoe\");\r\n");
      out.write("	        console.log(data);\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            type: \"GET\",\r\n");
      out.write("	            url: \"/shopbangiay-jsp-servlet/api-web-new\",\r\n");
      out.write("	            data: JSON.stringify(idShoe),\r\n");
      out.write("	            dataType: \"application/json\",\r\n");
      out.write("	            success: function(data) {\r\n");
      out.write("	                // Cập nhật thông tin chi tiết sản phẩm\r\n");
      out.write("	                console.log(data);\r\n");
      out.write("	                // Hiển thị modal\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function(xhr, status, error) {\r\n");
      out.write("	                console.error(\"Error: \" + error);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	</script> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/home.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("APIUrl");
      // /views/web/home.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/api-web-new");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/web/home.jsp(30,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/web/images/item-cart-01.jpg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/web/home.jsp(43,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/template/web/images/item-cart-02.jpg");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/web/home.jsp(56,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/template/web/images/item-cart-03.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/web/home.jsp(90,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/template/web/images/slide-01.jpg");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/web/home.jsp(116,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/template/web/images/slide-02.jpg");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/web/home.jsp(141,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/template/web/images/slide-03.jpg");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/web/home.jsp(177,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/template/web/images/banner-01.jpg");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/web/home.jsp(196,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/template/web/images/banner-02.jpg");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/web/home.jsp(216,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/template/web/images/banner-03.jpg");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/web/home.jsp(412,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /views/web/home.jsp(412,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/web/home.jsp(412,4) '${listShoes}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listShoes}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<div\r\n");
            out.write("						class=\"producttt col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women\">\r\n");
            out.write("						<!-- Block2 -->\r\n");
            out.write("						<div class=\"block2\">\r\n");
            out.write("							<div class=\"block2-pic hov-img0\">\r\n");
            out.write("								<img src=\"");
            if (_jspx_meth_c_005furl_005f10(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\"\r\n");
            out.write("									alt=\"IMG-PRODUCT\"> <a href=\"#\"\r\n");
            out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\"\r\n");
            out.write("									data-price=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.getPRICE()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.getID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-idshoes=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.getID_SHOE()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-nameshoes=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.getNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> Quick View </a>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
            out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
            out.write("									<a href=\"product-detail.html\"\r\n");
            out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.getNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </a> <span class=\"stext-105 cl3\">\r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.getPRICE()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("								</div>\r\n");
            out.write("\r\n");
            out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
            out.write("									<a href=\"#\"\r\n");
            out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
            out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
            out.write("										src=\"");
            if (_jspx_meth_c_005furl_005f11(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\"\r\n");
            out.write("										alt=\"ICON\"> <img\r\n");
            out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
            out.write("										src=\"");
            if (_jspx_meth_c_005furl_005f12(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\"\r\n");
            out.write("										alt=\"ICON\">\r\n");
            out.write("									</a>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /views/web/home.jsp(418,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/template/web/images/product-01.jpg");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /views/web/home.jsp(436,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/template/web/images/icons/icon-heart-01.png");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /views/web/home.jsp(439,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/template/web/images/icons/icon-heart-02.png");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f13 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f13_reused = false;
    try {
      _jspx_th_c_005furl_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f13.setParent(null);
      // /views/web/home.jsp(959,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f13.setValue("/template/web/images/icons/icon-close.png");
      int _jspx_eval_c_005furl_005f13 = _jspx_th_c_005furl_005f13.doStartTag();
      if (_jspx_th_c_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f13);
      _jspx_th_c_005furl_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f13, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f14 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f14_reused = false;
    try {
      _jspx_th_c_005furl_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f14.setParent(null);
      // /views/web/home.jsp(975,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f14.setValue("/template/web/images/product-detail-01.jpg");
      int _jspx_eval_c_005furl_005f14 = _jspx_th_c_005furl_005f14.doStartTag();
      if (_jspx_th_c_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f14);
      _jspx_th_c_005furl_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f14, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f15 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f15_reused = false;
    try {
      _jspx_th_c_005furl_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f15.setParent(null);
      // /views/web/home.jsp(988,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f15.setValue("/template/web/images/product-detail-02.jpg");
      int _jspx_eval_c_005furl_005f15 = _jspx_th_c_005furl_005f15.doStartTag();
      if (_jspx_th_c_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f15);
      _jspx_th_c_005furl_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f15, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f16 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f16_reused = false;
    try {
      _jspx_th_c_005furl_005f16.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f16.setParent(null);
      // /views/web/home.jsp(1001,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f16.setValue("/template/web/images/product-detail-03.jpg");
      int _jspx_eval_c_005furl_005f16 = _jspx_th_c_005furl_005f16.doStartTag();
      if (_jspx_th_c_005furl_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f16);
      _jspx_th_c_005furl_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f16, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f16_reused);
    }
    return false;
  }
}
