/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-12 09:44:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Product Detail</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("			initSlickSlider();\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<section class=\"sec-product-detail bg0 p-t-65 p-b-60\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6 col-lg-7 p-b-30\">\r\n");
      out.write("					<div class=\"p-l-25 p-r-30 p-lr-0-lg\">\r\n");
      out.write("						<div class=\"wrap-slick3 flex-sb flex-w\">\r\n");
      out.write("							<div class=\"wrap-slick3-dots\"></div>\r\n");
      out.write("							<div class=\"wrap-slick3-arrows flex-sb-m flex-w\"></div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"slick3 gallery-lb\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6 col-lg-5 p-b-30\">\r\n");
      out.write("					<div class=\"p-r-50 p-t-5 p-lr-0-lg click-js-addcart-detail\">\r\n");
      out.write("						<h4 class=\"mtext-105 cl2 js-name-detail p-b-14\" id=\"nameShoe\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detall_shoes.getNAME()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("						<span class=\"mtext-106 cl2\" id=\"PRICE\">\r\n");
      out.write("							$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detall_shoes.getPRICE()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"stext-102 cl3 p-t-23\">Nulla eget sem vitae eros\r\n");
      out.write("							pharetra viverra. Nam vitae luctus ligula. Mauris consequat\r\n");
      out.write("							ornare feugiat.</p>\r\n");
      out.write("\r\n");
      out.write("						<!--  -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-33\">\r\n");
      out.write("							<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("								<div class=\"size-203 flex-c-m respon6\">Size</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"size-204 respon6-next\">\r\n");
      out.write("									<div class=\"rs1-select2 bor8 bg0\">\r\n");
      out.write("										<select class=\"js-select2\" name=\"sizes\" id=\"sizes\">\r\n");
      out.write("											<option>Choose an option</option>\r\n");
      out.write("											");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										</select>\r\n");
      out.write("										<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("								<div class=\"size-203 flex-c-m respon6\">Color</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"size-204 respon6-next\">\r\n");
      out.write("									<div class=\"rs1-select2 bor8 bg0\">\r\n");
      out.write("										<select class=\"js-select2\" name=\"color\" id=\"color\">\r\n");
      out.write("											<option>Choose an option</option>\r\n");
      out.write("											");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										</select>\r\n");
      out.write("										<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"flex-w flex-r-m p-b-10\">\r\n");
      out.write("								<div class=\"size-204 flex-w flex-m respon6-next\">\r\n");
      out.write("									<div class=\"wrap-num-product flex-w m-r-20 m-tb-10\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m\">\r\n");
      out.write("											<i class=\"fs-16 zmdi zmdi-minus\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<input class=\"mtext-104 cl3 txt-center num-product\"\r\n");
      out.write("											type=\"number\" name=\"num-product\" id=\"num-product\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m\">\r\n");
      out.write("											<i class=\"fs-16 zmdi zmdi-plus\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<input type=\"hidden\" name=\"iddf\" id=\"iddf\" value=\"\"> <input\r\n");
      out.write("										type=\"hidden\" name=\"id_Shoe\" id=\"id_Shoe\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("									<button\r\n");
      out.write("										class=\"flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail\">\r\n");
      out.write("										Add to cart</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!--  -->\r\n");
      out.write("						<div class=\"flex-w flex-m p-l-100 p-t-40 respon7\">\r\n");
      out.write("							<div class=\"flex-m bor9 p-r-10 m-r-11\">\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100\"\r\n");
      out.write("									data-tooltip=\"Add to Wishlist\"> <i\r\n");
      out.write("									class=\"zmdi zmdi-favorite\"></i>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<a href=\"#\"\r\n");
      out.write("								class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("								data-tooltip=\"Facebook\"> <i class=\"fa fa-facebook\"></i>\r\n");
      out.write("							</a> <a href=\"#\"\r\n");
      out.write("								class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("								data-tooltip=\"Twitter\"> <i class=\"fa fa-twitter\"></i>\r\n");
      out.write("							</a> <a href=\"#\"\r\n");
      out.write("								class=\"fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100\"\r\n");
      out.write("								data-tooltip=\"Google Plus\"> <i class=\"fa fa-google-plus\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"bor10 m-t-50 p-t-43 p-b-40\">\r\n");
      out.write("				<!-- Tab01 -->\r\n");
      out.write("				<div class=\"tab01\">\r\n");
      out.write("					<!-- Nav tabs -->\r\n");
      out.write("					<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("						<li class=\"nav-item p-b-10\"><a class=\"nav-link active\"\r\n");
      out.write("							data-toggle=\"tab\" href=\"#description\" role=\"tab\">Description</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item p-b-10\"><a class=\"nav-link\"\r\n");
      out.write("							data-toggle=\"tab\" href=\"#information\" role=\"tab\">Additional\r\n");
      out.write("								information</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"nav-item p-b-10\"><a class=\"nav-link\"\r\n");
      out.write("							data-toggle=\"tab\" href=\"#reviews\" role=\"tab\">Reviews (1)</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("					<!-- Tab panes -->\r\n");
      out.write("					<div class=\"tab-content p-t-43\">\r\n");
      out.write("						<!-- - -->\r\n");
      out.write("						<div class=\"tab-pane fade show active\" id=\"description\"\r\n");
      out.write("							role=\"tabpanel\">\r\n");
      out.write("							<div class=\"how-pos2 p-lr-15-md\">\r\n");
      out.write("								<p class=\"stext-102 cl6\">Aenean sit amet gravida nisi. Nam\r\n");
      out.write("									fermentum est felis, quis feugiat nunc fringilla sit amet. Ut\r\n");
      out.write("									in blandit ipsum. Quisque luctus dui at ante aliquet, in\r\n");
      out.write("									hendrerit lectus interdum. Morbi elementum sapien rhoncus\r\n");
      out.write("									pretium maximus. Nulla lectus enim, cursus et elementum sed,\r\n");
      out.write("									sodales vitae eros. Ut ex quam, porta consequat interdum in,\r\n");
      out.write("									faucibus eu velit. Quisque rhoncus ex ac libero varius\r\n");
      out.write("									molestie. Aenean tempor sit amet orci nec iaculis. Cras sit\r\n");
      out.write("									amet nulla libero. Curabitur dignissim, nunc nec laoreet\r\n");
      out.write("									consequat, purus nunc porta lacus, vel efficitur tellus augue\r\n");
      out.write("									in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non\r\n");
      out.write("									tempor erat. Duis in egestas nunc.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- - -->\r\n");
      out.write("						<div class=\"tab-pane fade\" id=\"information\" role=\"tabpanel\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-sm-10 col-md-8 col-lg-6 m-lr-auto\">\r\n");
      out.write("									<ul class=\"p-lr-28 p-lr-15-sm\">\r\n");
      out.write("										<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("											class=\"stext-102 cl3 size-205\"> Weight </span> <span\r\n");
      out.write("											class=\"stext-102 cl6 size-206\"> 0.79 kg </span></li>\r\n");
      out.write("\r\n");
      out.write("										<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("											class=\"stext-102 cl3 size-205\"> Dimensions </span> <span\r\n");
      out.write("											class=\"stext-102 cl6 size-206\"> 110 x 33 x 100 cm </span></li>\r\n");
      out.write("\r\n");
      out.write("										<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("											class=\"stext-102 cl3 size-205\"> Materials </span> <span\r\n");
      out.write("											class=\"stext-102 cl6 size-206\"> 60% cotton </span></li>\r\n");
      out.write("\r\n");
      out.write("										<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("											class=\"stext-102 cl3 size-205\"> Color </span> <span\r\n");
      out.write("											class=\"stext-102 cl6 size-206\"> Black, Blue, Grey,\r\n");
      out.write("												Green, Red, White </span></li>\r\n");
      out.write("\r\n");
      out.write("										<li class=\"flex-w flex-t p-b-7\"><span\r\n");
      out.write("											class=\"stext-102 cl3 size-205\"> Size </span> <span\r\n");
      out.write("											class=\"stext-102 cl6 size-206\"> XL, L, M, S </span></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- - -->\r\n");
      out.write("						<div class=\"tab-pane fade\" id=\"reviews\" role=\"tabpanel\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-sm-10 col-md-8 col-lg-6 m-lr-auto\">\r\n");
      out.write("									<div class=\"p-b-30 m-lr-15-sm\">\r\n");
      out.write("										<!-- Review -->\r\n");
      out.write("										<div class=\"flex-w flex-t p-b-68\">\r\n");
      out.write("											<div class=\"wrap-pic-s size-109 bor0 of-hidden m-r-18 m-t-6\">\r\n");
      out.write("												<img src=\"images/avatar-01.jpg\" alt=\"AVATAR\">\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"size-207\">\r\n");
      out.write("												<div class=\"flex-w flex-sb-m p-b-17\">\r\n");
      out.write("													<span class=\"mtext-107 cl2 p-r-20\"> Ariana Grande </span> <span\r\n");
      out.write("														class=\"fs-18 cl11\"> <i class=\"zmdi zmdi-star\"></i>\r\n");
      out.write("														<i class=\"zmdi zmdi-star\"></i> <i class=\"zmdi zmdi-star\"></i>\r\n");
      out.write("														<i class=\"zmdi zmdi-star\"></i> <i\r\n");
      out.write("														class=\"zmdi zmdi-star-half\"></i>\r\n");
      out.write("													</span>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<p class=\"stext-102 cl6\">Quod autem in homine\r\n");
      out.write("													praestantissimum atque optimum est, id deseruit. Apud\r\n");
      out.write("													ceteros autem philosophos</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<!-- Add review -->\r\n");
      out.write("										<form class=\"w-full\">\r\n");
      out.write("											<h5 class=\"mtext-108 cl2 p-b-7\">Add a review</h5>\r\n");
      out.write("\r\n");
      out.write("											<p class=\"stext-102 cl6\">Your email address will not be\r\n");
      out.write("												published. Required fields are marked *</p>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"flex-w flex-m p-t-50 p-b-23\">\r\n");
      out.write("												<span class=\"stext-102 cl3 m-r-16\"> Your Rating </span> <span\r\n");
      out.write("													class=\"wrap-rating fs-18 cl11 pointer\"> <i\r\n");
      out.write("													class=\"item-rating pointer zmdi zmdi-star-outline\"></i> <i\r\n");
      out.write("													class=\"item-rating pointer zmdi zmdi-star-outline\"></i> <i\r\n");
      out.write("													class=\"item-rating pointer zmdi zmdi-star-outline\"></i> <i\r\n");
      out.write("													class=\"item-rating pointer zmdi zmdi-star-outline\"></i> <i\r\n");
      out.write("													class=\"item-rating pointer zmdi zmdi-star-outline\"></i> <input\r\n");
      out.write("													class=\"dis-none\" type=\"number\" name=\"rating\">\r\n");
      out.write("												</span>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"row p-b-25\">\r\n");
      out.write("												<div class=\"col-12 p-b-5\">\r\n");
      out.write("													<label class=\"stext-102 cl3\" for=\"review\">Your\r\n");
      out.write("														review</label>\r\n");
      out.write("													<textarea\r\n");
      out.write("														class=\"size-110 bor8 stext-102 cl2 p-lr-20 p-tb-10\"\r\n");
      out.write("														id=\"review\" name=\"review\"></textarea>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-sm-6 p-b-5\">\r\n");
      out.write("													<label class=\"stext-102 cl3\" for=\"name\">Name</label> <input\r\n");
      out.write("														class=\"size-111 bor8 stext-102 cl2 p-lr-20\" id=\"name\"\r\n");
      out.write("														type=\"text\" name=\"name\">\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"col-sm-6 p-b-5\">\r\n");
      out.write("													<label class=\"stext-102 cl3\" for=\"email\">Email</label> <input\r\n");
      out.write("														class=\"size-111 bor8 stext-102 cl2 p-lr-20\" id=\"email\"\r\n");
      out.write("														type=\"text\" name=\"email\">\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<button\r\n");
      out.write("												class=\"flex-c-m stext-101 cl0 size-112 bg7 bor11 hov-btn3 p-lr-15 trans-04 m-b-10\">\r\n");
      out.write("												Submit</button>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"bg6 flex-c-m flex-w size-302 m-t-73 p-tb-15\">\r\n");
      out.write("			<span class=\"stext-107 cl6 p-lr-25\"> SKU: JAK-01 </span> <span\r\n");
      out.write("				class=\"stext-107 cl6 p-lr-25\"> Categories: Jacket, Men </span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"sec-relate-product bg0 p-t-45 p-b-105\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"p-b-45\">\r\n");
      out.write("				<h3 class=\"ltext-106 cl5 txt-center\">Related Products</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Slide2 -->\r\n");
      out.write("			<div class=\"wrap-slick2\">\r\n");
      out.write("				<div class=\"slick2\">\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-01.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Esprit Ruffle Shirt </a> <span class=\"stext-105 cl3\">\r\n");
      out.write("										$16.64 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-02.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Herschel supply </a> <span class=\"stext-105 cl3\"> $35.31 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-03.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Only Check Trouser </a> <span class=\"stext-105 cl3\"> $25.50\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-04.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Classic Trench Coat </a> <span class=\"stext-105 cl3\">\r\n");
      out.write("										$75.00 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-05.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Front Pocket Jumper </a> <span class=\"stext-105 cl3\">\r\n");
      out.write("										$34.75 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-06.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Vintage Inspired Classic </a> <span class=\"stext-105 cl3\">\r\n");
      out.write("										$93.20 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-07.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Shirt in Stretch Cotton </a> <span class=\"stext-105 cl3\">\r\n");
      out.write("										$52.66 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-slick2 p-l-15 p-r-15 p-t-15 p-b-15\">\r\n");
      out.write("						<!-- Block2 -->\r\n");
      out.write("						<div class=\"block2\">\r\n");
      out.write("							<div class=\"block2-pic hov-img0\">\r\n");
      out.write("								<img src=\"images/product-08.jpg\" alt=\"IMG-PRODUCT\"> <a\r\n");
      out.write("									href=\"#\"\r\n");
      out.write("									class=\"block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1\">\r\n");
      out.write("									Quick View </a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"block2-txt flex-w flex-t p-t-14\">\r\n");
      out.write("								<div class=\"block2-txt-child1 flex-col-l \">\r\n");
      out.write("									<a href=\"product-detail.html\"\r\n");
      out.write("										class=\"stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6\">\r\n");
      out.write("										Pieces Metallic Printed </a> <span class=\"stext-105 cl3\">\r\n");
      out.write("										$18.96 </span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"block2-txt-child2 flex-r p-t-3\">\r\n");
      out.write("									<a href=\"#\"\r\n");
      out.write("										class=\"btn-addwish-b2 dis-block pos-relative js-addwish-b2\">\r\n");
      out.write("										<img class=\"icon-heart1 dis-block trans-04\"\r\n");
      out.write("										src=\"images/icons/icon-heart-01.png\" alt=\"ICON\"> <img\r\n");
      out.write("										class=\"icon-heart2 dis-block trans-04 ab-t-l\"\r\n");
      out.write("										src=\"images/icons/icon-heart-02.png\" alt=\"ICON\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/web/productdetail.jsp(26,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("image");
      // /views/web/productdetail.jsp(26,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/web/productdetail.jsp(26,8) '${images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("									<div class=\"item-slick3\" id=\"imageDataThumb1\"\r\n");
            out.write("										data-thumb=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.getID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("										<div class=\"wrap-pic-w pos-relative\">\r\n");
            out.write("											<img id=\"imageIMG1\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.getID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"IMG-PRODUCT\">\r\n");
            out.write("											<a id=\"imageA1\"\r\n");
            out.write("												class=\"flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04\"\r\n");
            out.write("												href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.getID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <i class=\"fa fa-expand\"></i>\r\n");
            out.write("											</a>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /views/web/productdetail.jsp(67,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("sizes");
      // /views/web/productdetail.jsp(67,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/views/web/productdetail.jsp(67,11) '${size}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${size}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("												<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sizes.getSIZE()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("											");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /views/web/productdetail.jsp(83,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("sizes");
      // /views/web/productdetail.jsp(83,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/views/web/productdetail.jsp(83,11) '${colors}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${colors}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("												<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sizes.getNAMEE()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("											");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
