/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-13 18:24:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shopingCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Shoping Cart</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- breadcrumb -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg\">\r\n");
      out.write("			<a href=\"/shopbangiay-jsp-servlet/trang-chu\"\r\n");
      out.write("				class=\"stext-109 cl8 hov-cl1 trans-04\"> Home <i\r\n");
      out.write("				class=\"fa fa-angle-right m-l-9 m-r-10\" aria-hidden=\"true\"></i>\r\n");
      out.write("			</a> <span class=\"stext-109 cl4\"> Shoping Cart </span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Shoping Cart -->\r\n");
      out.write("<!-- 	<form class=\"bg0 p-t-75 p-b-85\"> -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-10 col-xl-7 m-lr-auto m-b-50\">\r\n");
      out.write("					<div class=\"m-l-25 m-r--38 m-lr-0-xl\">\r\n");
      out.write("						<div class=\"wrap-table-shopping-cart\">\r\n");
      out.write("							<table class=\"table-shopping-cart\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr class=\"table_head\">\r\n");
      out.write("									<th class=\"column-1\">Product</th>\r\n");
      out.write("									<th class=\"column-2\"></th>\r\n");
      out.write("									<th class=\"column-3\">Price</th>\r\n");
      out.write("									<th class=\"column-4\">Quantity</th>\r\n");
      out.write("									<th class=\"column-5\">Total</th>\r\n");
      out.write("									<th class=\"column-6\"></th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm\">\r\n");
      out.write("							<div class=\"flex-w flex-m m-r-20 m-tb-5\">\r\n");
      out.write("								<input\r\n");
      out.write("									class=\"stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5\"\r\n");
      out.write("									type=\"text\" name=\"coupon\" placeholder=\"Coupon Code\">\r\n");
      out.write("\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5\">\r\n");
      out.write("									Apply coupon</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10 UpdateCart\">\r\n");
      out.write("								Update Cart</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm\">\r\n");
      out.write("						<h4 class=\"mtext-109 cl2 p-b-30\">Cart Totals</h4>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"flex-w flex-t bor12 p-b-13\">\r\n");
      out.write("							<div class=\"size-208\">\r\n");
      out.write("								<span class=\"stext-110 cl2\"> Subtotal: </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"size-209\">\r\n");
      out.write("								<span class=\"mtext-110 cl2 tongtien\"> $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tongtien}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"flex-w flex-t bor12 p-t-15 p-b-30\">\r\n");
      out.write("							<div class=\"size-208 w-full-ssm\">\r\n");
      out.write("								<span class=\"stext-110 cl2\"> Shipping: </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"size-209 p-r-18 p-r-0-sm w-full-ssm\">\r\n");
      out.write("								<p class=\"stext-111 cl6 p-t-2\">There are no shipping methods\r\n");
      out.write("									available. Please double check your address, or contact us if\r\n");
      out.write("									you need any help.</p>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"p-t-15\">\r\n");
      out.write("									<span class=\"stext-112 cl8\"> Calculate Shipping </span>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"rs1-select2 rs2-select2 bor8 bg0 m-b-12 m-t-9\">\r\n");
      out.write("										<select class=\"js-select2\" name=\"time\">\r\n");
      out.write("											<option>Select a Province, City ...</option>\r\n");
      out.write("											<option>HCM</option>\r\n");
      out.write("											<option>HN</option>\r\n");
      out.write("										</select>\r\n");
      out.write("										<div class=\"dropDownSelect2\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"bor8 bg0 m-b-12\">\r\n");
      out.write("										<input class=\"stext-111 cl8 plh3 size-111 p-lr-15\" type=\"text\"\r\n");
      out.write("											name=\"state\" placeholder=\"District\">\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"bor8 bg0 m-b-22\">\r\n");
      out.write("										<input class=\"stext-111 cl8 plh3 size-111 p-lr-15\" type=\"text\"\r\n");
      out.write("											name=\"postcode\" placeholder=\"Commune\">\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"flex-w\">\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"flex-c-m stext-101 cl2 size-115 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer\">\r\n");
      out.write("											Update Totals</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"flex-w flex-t p-t-27 p-b-33\">\r\n");
      out.write("							<div class=\"size-208\">\r\n");
      out.write("								<span class=\"mtext-101 cl2\"> Total: </span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"size-209 p-t-1\">\r\n");
      out.write("								<span class=\"mtext-110 cl2 tongtien\"> $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tongtien}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button\r\n");
      out.write("							class=\"flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer mua-Carts\">\r\n");
      out.write("							Proceed to Checkout</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("<!-- 	</form> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/web/shopingCart.jsp(41,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cart");
      // /views/web/shopingCart.jsp(41,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/web/shopingCart.jsp(41,8) '${Carts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Carts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<tr class=\"table_row\">\r\n");
            out.write("										<td class=\"column-1\">\r\n");
            out.write("											<div class=\"how-itemcart1\">\r\n");
            out.write("												<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getImage_url()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"IMG\">\r\n");
            out.write("											</div>\r\n");
            out.write("										</td>\r\n");
            out.write("										<td class=\"column-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getShoe_name()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td class=\"column-3\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getPrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td class=\"column-4\">\r\n");
            out.write("											<div class=\"wrap-num-product flex-w m-l-auto m-r-0\">\r\n");
            out.write("												<div\r\n");
            out.write("													class=\"btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m\" onclick = \"btnnumproductdown(this)\">\r\n");
            out.write("													<i class=\"fs-16 zmdi zmdi-minus\"></i>\r\n");
            out.write("												</div>\r\n");
            out.write("\r\n");
            out.write("												<input class=\"mtext-104 cl3 txt-center num-product num-product-cart\"\r\n");
            out.write("													data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getIDCARTS()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" type=\"number\" name=\"num-product1\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getQUANTITY()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\r\n");
            out.write("												<div\r\n");
            out.write("													class=\"btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m\" onclick = \"btnnumproductup(this)\">\r\n");
            out.write("													<i class=\"fs-16 zmdi zmdi-plus\"></i>\r\n");
            out.write("												</div>\r\n");
            out.write("											</div>\r\n");
            out.write("										</td>\r\n");
            out.write("										<td class=\"column-5\"> $");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getQUANTITY() * cart.getPrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td class=\"column-6\" onclick = \"DeleteCart(this)\"><div data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.getIDCARTS()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10 btnXoaCart\"><i class=\"fa-solid fa-trash\"></i></div></td>\r\n");
            out.write("									</tr>\r\n");
            out.write("\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
