/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-18 04:43:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Topbar Start -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("	<div class=\"row bg-secondary py-1 px-xl-5\">\r\n");
      out.write("		<div class=\"col-lg-6 d-none d-lg-block\">\r\n");
      out.write("			<div class=\"d-inline-flex align-items-center h-100\">\r\n");
      out.write("				<a class=\"text-body mr-3\" href=\"\">About</a> <a\r\n");
      out.write("					class=\"text-body mr-3\" href=\"\">Contact</a> <a\r\n");
      out.write("					class=\"text-body mr-3\" href=\"\">Help</a> <a class=\"text-body mr-3\"\r\n");
      out.write("					href=\"\">FAQs</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-lg-6 text-center text-lg-right\">\r\n");
      out.write("			<div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("				<div class=\"btn-group\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-sm btn-light dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\">My Account</button>\r\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">Sign in</button>\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">Sign up</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn-group mx-2\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-sm btn-light dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\">USD</button>\r\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">EUR</button>\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">GBP</button>\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">CAD</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn-group\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-sm btn-light dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\">EN</button>\r\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">FR</button>\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">AR</button>\r\n");
      out.write("						<button class=\"dropdown-item\" type=\"button\">RU</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"d-inline-flex align-items-center d-block d-lg-none\">\r\n");
      out.write("				<a href=\"\" class=\"btn px-0 ml-2\"> <i\r\n");
      out.write("					class=\"fas fa-heart text-dark\"></i> <span\r\n");
      out.write("					class=\"badge text-dark border border-dark rounded-circle\"\r\n");
      out.write("					style=\"padding-bottom: 2px;\">0</span>\r\n");
      out.write("				</a> <a href=\"\" class=\"btn px-0 ml-2\"> <i\r\n");
      out.write("					class=\"fas fa-shopping-cart text-dark\"></i> <span\r\n");
      out.write("					class=\"badge text-dark border border-dark rounded-circle\"\r\n");
      out.write("					style=\"padding-bottom: 2px;\">0</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex\">\r\n");
      out.write("		<div class=\"col-lg-4\">\r\n");
      out.write("			<a href=\"\" class=\"text-decoration-none\"> <span\r\n");
      out.write("				class=\"h1 text-uppercase text-primary bg-dark px-2\">Multi</span> <span\r\n");
      out.write("				class=\"h1 text-uppercase text-dark bg-primary px-2 ml-n1\">Shop</span>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-lg-4 col-6 text-left\">\r\n");
      out.write("			<form action=\"\">\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\"\r\n");
      out.write("						placeholder=\"Search for products\">\r\n");
      out.write("					<div class=\"input-group-append\">\r\n");
      out.write("						<span class=\"input-group-text bg-transparent text-primary\">\r\n");
      out.write("							<i class=\"fa fa-search\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-lg-4 col-6 text-right\">\r\n");
      out.write("			<p class=\"m-0\">Customer Service</p>\r\n");
      out.write("			<h5 class=\"m-0\">+012 345 6789</h5>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Topbar End -->\r\n");
      out.write("<!-- Navbar Start -->\r\n");
      out.write("<div class=\"container-fluid bg-dark mb-30\">\r\n");
      out.write("	<div class=\"row px-xl-5\">\r\n");
      out.write("		<div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("			<a\r\n");
      out.write("				class=\"btn d-flex align-items-center justify-content-between bg-primary w-100\"\r\n");
      out.write("				data-toggle=\"collapse\" href=\"#navbar-vertical\"\r\n");
      out.write("				style=\"height: 65px; padding: 0 30px;\">\r\n");
      out.write("				<h6 class=\"text-dark m-0\">\r\n");
      out.write("					<i class=\"fa fa-bars mr-2\"></i>Categories\r\n");
      out.write("				</h6> <i class=\"fa fa-angle-down text-dark\"></i>\r\n");
      out.write("			</a>\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light\"\r\n");
      out.write("				id=\"navbar-vertical\" style=\"width: calc(100% - 30px); z-index: 999;\">\r\n");
      out.write("				<div class=\"navbar-nav w-100\">\r\n");
      out.write("					<div class=\"nav-item dropdown dropright\">\r\n");
      out.write("						<a href=\"#\" class=\"nav-link dropdown-toggle\"\r\n");
      out.write("							data-toggle=\"dropdown\">Dresses <i\r\n");
      out.write("							class=\"fa fa-angle-right float-right mt-1\"></i></a>\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"dropdown-menu position-absolute rounded-0 border-0 m-0\">\r\n");
      out.write("							<a href=\"\" class=\"dropdown-item\">Men's Dresses</a> <a href=\"\"\r\n");
      out.write("								class=\"dropdown-item\">Women's Dresses</a> <a href=\"\"\r\n");
      out.write("								class=\"dropdown-item\">Baby's Dresses</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a href=\"\" class=\"nav-item nav-link\">Shirts</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Jeans</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Swimwear</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Sleepwear</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Sportswear</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Jumpsuits</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Blazers</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Jackets</a> <a href=\"\"\r\n");
      out.write("						class=\"nav-item nav-link\">Shoes</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-lg-9\">\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0\">\r\n");
      out.write("				<a href=\"\" class=\"text-decoration-none d-block d-lg-none\"> <span\r\n");
      out.write("					class=\"h1 text-uppercase text-dark bg-light px-2\">Multi</span> <span\r\n");
      out.write("					class=\"h1 text-uppercase text-light bg-primary px-2 ml-n1\">Shop</span>\r\n");
      out.write("				</a>\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\"#navbarCollapse\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"collapse navbar-collapse justify-content-between\"\r\n");
      out.write("					id=\"navbarCollapse\">\r\n");
      out.write("					<div class=\"navbar-nav mr-auto py-0\">\r\n");
      out.write("						<a href=\"index.html\" class=\"nav-item nav-link active\">Home</a> <a\r\n");
      out.write("							href=\"shop.html\" class=\"nav-item nav-link\">Shop</a> <a\r\n");
      out.write("							href=\"detail.html\" class=\"nav-item nav-link\">Shop Detail</a>\r\n");
      out.write("						<div class=\"nav-item dropdown\">\r\n");
      out.write("							<a href=\"#\" class=\"nav-link dropdown-toggle\"\r\n");
      out.write("								data-toggle=\"dropdown\">Pages <i\r\n");
      out.write("								class=\"fa fa-angle-down mt-1\"></i></a>\r\n");
      out.write("							<div class=\"dropdown-menu bg-primary rounded-0 border-0 m-0\">\r\n");
      out.write("								<a href=\"cart.html\" class=\"dropdown-item\">Shopping Cart</a> <a\r\n");
      out.write("									href=\"checkout.html\" class=\"dropdown-item\">Checkout</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"contact.html\" class=\"nav-item nav-link\">Contact</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"navbar-nav ml-auto py-0 d-none d-lg-block\">\r\n");
      out.write("						<a href=\"\" class=\"btn px-0\"> <i\r\n");
      out.write("							class=\"fas fa-heart text-primary\"></i> <span\r\n");
      out.write("							class=\"badge text-secondary border border-secondary rounded-circle\"\r\n");
      out.write("							style=\"padding-bottom: 2px;\">0</span>\r\n");
      out.write("						</a> <a href=\"\" class=\"btn px-0 ml-3\"> <i\r\n");
      out.write("							class=\"fas fa-shopping-cart text-primary\"></i> <span\r\n");
      out.write("							class=\"badge text-secondary border border-secondary rounded-circle\"\r\n");
      out.write("							style=\"padding-bottom: 2px;\">0</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Navbar End -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
