/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-14 08:12:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chitietgiay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Chi tiết giày</title> .form-container { max-width: 600px; margin:\r\n");
      out.write("50px auto; padding: 30px; background-color: #fff; border-radius: 10px;\r\n");
      out.write("box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); } .form-title { text-align:\r\n");
      out.write("center; margin-bottom: 30px; font-size: 24px; color: #333; font-weight:\r\n");
      out.write("bold; } .form-group label { font-weight: bold; color: #555; }\r\n");
      out.write(".btn-primary { background-color: #007bff; border-color: #007bff; }\r\n");
      out.write(".btn-primary:hover { background-color: #0056b3; border-color: #0056b3; }\r\n");
      out.write(".file-list { margin-top: 20px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("        <a class=\"m-0 float-right btn btn-danger btn-sm\" href=\"/shopbangiay-jsp-servlet/admin-quanly-giay\">\r\n");
      out.write("            Quay trở lại <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <form>\r\n");
      out.write("            <!-- Image Upload Inputs -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"imageUpload\">Upload Hình Ảnh</label>\r\n");
      out.write("                <input type=\"file\" class=\"form-control-file\" id=\"imageUpload\" accept=\"image/*\" multiple>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"fileList\" class=\"file-list\">\r\n");
      out.write("                <ul class=\"list-group\"></ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Text Input Fields -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputMaGiay\">Mã giày</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"inputMaGiay\" placeholder=\"Nhập dữ liệu vào đây\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputTenGiay\">Tên giày</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"inputTenGiay\" placeholder=\"Nhập dữ liệu vào đây\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputChiTiet\">Chi tiết</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"inputChiTiet\" placeholder=\"Nhập dữ liệu vào đây\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputGia\">Giá</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"inputGia\" placeholder=\"Nhập dữ liệu vào đây\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputSoLuong\">Số lượng</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"inputSoLuong\" placeholder=\"Nhập dữ liệu vào đây\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"selectMau\">Màu sắc</label>\r\n");
      out.write("                <select class=\"form-control\" id=\"selectMau\">\r\n");
      out.write("                    <option>Chọn màu</option>\r\n");
      out.write("                    <option>Đỏ</option>\r\n");
      out.write("                    <option>Xanh</option>\r\n");
      out.write("                    <option>Trắng</option>\r\n");
      out.write("                    <option>Xám</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Button Group -->\r\n");
      out.write("            <div class=\"btn-group\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success btn-block\">Thêm</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn-group\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-warning btn-block\">Sửa</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn-group\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger btn-block\">Xóa</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document)\r\n");
      out.write("				.ready(\r\n");
      out.write("						function() {\r\n");
      out.write("							$('#imageUpload')\r\n");
      out.write("									.on(\r\n");
      out.write("											'change',\r\n");
      out.write("											function() {\r\n");
      out.write("												var fileList = $('#fileList');\r\n");
      out.write("												fileList.empty();\r\n");
      out.write("												var files = this.files;\r\n");
      out.write("												if (files.length > 0) {\r\n");
      out.write("													var list = $('<ul class=\"list-group\"></ul>');\r\n");
      out.write("													for (var i = 0; i < files.length; i++) {\r\n");
      out.write("														var fileName = files[i].name;\r\n");
      out.write("														var fileItem = $(\r\n");
      out.write("																'<li class=\"list-group-item\"></li>')\r\n");
      out.write("																.text(fileName);\r\n");
      out.write("														list.append(fileItem);\r\n");
      out.write("													}\r\n");
      out.write("													fileList.append(list);\r\n");
      out.write("												}\r\n");
      out.write("												var liTexts = [];\r\n");
      out.write("												$('#fileList li')\r\n");
      out.write("														.each(\r\n");
      out.write("																function() {\r\n");
      out.write("																	liTexts\r\n");
      out.write("																			.push($(\r\n");
      out.write("																					this)\r\n");
      out.write("																					.text());\r\n");
      out.write("																});\r\n");
      out.write("												console.log(liTexts)\r\n");
      out.write("											});\r\n");
      out.write("						});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
