/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-27 16:18:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Trang chu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid\" id=\"container-wrapper\">\r\n");
      out.write("		<div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("			<h1 class=\"h3 mb-0 text-gray-800\">Dashboard</h1>\r\n");
      out.write("			<ol class=\"breadcrumb\">\r\n");
      out.write("				<li class=\"breadcrumb-item\"><a href=\"./\">Home</a></li>\r\n");
      out.write("				<li class=\"breadcrumb-item active\" aria-current=\"page\">Dashboard</li>\r\n");
      out.write("			</ol>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row mb-3\">\r\n");
      out.write("			<!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Earnings\r\n");
      out.write("									(Monthly)</div>\r\n");
      out.write("								<div class=\"h5 mb-0 font-weight-bold text-gray-800\">$40,000</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\">\r\n");
      out.write("									<span class=\"text-success mr-2\"><i\r\n");
      out.write("										class=\"fa fa-arrow-up\"></i> 3.48%</span> <span>Since last\r\n");
      out.write("										month</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-calendar fa-2x text-primary\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Earnings (Annual) Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row no-gutters align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Sales</div>\r\n");
      out.write("								<div class=\"h5 mb-0 font-weight-bold text-gray-800\">650</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\">\r\n");
      out.write("									<span class=\"text-success mr-2\"><i\r\n");
      out.write("										class=\"fas fa-arrow-up\"></i> 12%</span> <span>Since last years</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-shopping-cart fa-2x text-success\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- New User Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row no-gutters align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">New\r\n");
      out.write("									User</div>\r\n");
      out.write("								<div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">366</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\">\r\n");
      out.write("									<span class=\"text-success mr-2\"><i\r\n");
      out.write("										class=\"fas fa-arrow-up\"></i> 20.4%</span> <span>Since last\r\n");
      out.write("										month</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-users fa-2x text-info\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Pending Requests Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row no-gutters align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Pending\r\n");
      out.write("									Requests</div>\r\n");
      out.write("								<div class=\"h5 mb-0 font-weight-bold text-gray-800\">18</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\">\r\n");
      out.write("									<span class=\"text-danger mr-2\"><i\r\n");
      out.write("										class=\"fas fa-arrow-down\"></i> 1.10%</span> <span>Since\r\n");
      out.write("										yesterday</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-comments fa-2x text-warning\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Area Chart -->\r\n");
      out.write("			<div class=\"col-xl-8 col-lg-7\">\r\n");
      out.write("				<div class=\"card mb-4\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-primary\">Monthly Recap\r\n");
      out.write("							Report</h6>\r\n");
      out.write("						<div class=\"dropdown no-arrow\">\r\n");
      out.write("							<a class=\"dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("								id=\"dropdownMenuLink\" data-toggle=\"dropdown\"\r\n");
      out.write("								aria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("								class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("								aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("								<div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("									class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"chart-area\">\r\n");
      out.write("							<canvas id=\"myAreaChart\"></canvas>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Pie Chart -->\r\n");
      out.write("			<div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("				<div class=\"card mb-4\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-primary\">Products Sold</h6>\r\n");
      out.write("						<div class=\"dropdown no-arrow\">\r\n");
      out.write("							<a class=\"dropdown-toggle btn btn-primary btn-sm\" href=\"#\"\r\n");
      out.write("								role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\"\r\n");
      out.write("								aria-haspopup=\"true\" aria-expanded=\"false\"> Month <i\r\n");
      out.write("								class=\"fas fa-chevron-down\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("								aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("								<div class=\"dropdown-header\">Select Periode</div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\">Today</a> <a\r\n");
      out.write("									class=\"dropdown-item\" href=\"#\">Week</a> <a\r\n");
      out.write("									class=\"dropdown-item active\" href=\"#\">Month</a> <a\r\n");
      out.write("									class=\"dropdown-item\" href=\"#\">This Year</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Oblong T-Shirt\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>600 of 800 Items</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-warning\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 80%\" aria-valuenow=\"80\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Gundam 90'Editions\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>500 of 800 Items</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-success\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 70%\" aria-valuenow=\"70\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Rounded Hat\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>455 of 800 Items</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-danger\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 55%\" aria-valuenow=\"55\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Indomie Goreng\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>400 of 800 Items</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-info\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 50%\" aria-valuenow=\"50\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Remote Control Car Racing\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>200 of 800 Items</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-success\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 30%\" aria-valuenow=\"30\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-footer text-center\">\r\n");
      out.write("						<a class=\"m-0 small text-primary card-link\" href=\"#\">View More\r\n");
      out.write("							<i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Invoice Example -->\r\n");
      out.write("			<div class=\"col-xl-8 col-lg-7 mb-4\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-primary\">Invoice</h6>\r\n");
      out.write("						<a class=\"m-0 float-right btn btn-danger btn-sm\" href=\"#\">View\r\n");
      out.write("							More <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table align-items-center table-flush\">\r\n");
      out.write("							<thead class=\"thead-light\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Order ID</th>\r\n");
      out.write("									<th>Customer</th>\r\n");
      out.write("									<th>Item</th>\r\n");
      out.write("									<th>Status</th>\r\n");
      out.write("									<th>Action</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td><a href=\"#\">RA0449</a></td>\r\n");
      out.write("									<td>Udin Wayang</td>\r\n");
      out.write("									<td>Nasi Padang</td>\r\n");
      out.write("									<td><span class=\"badge badge-success\">Delivered</span></td>\r\n");
      out.write("									<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Detail</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td><a href=\"#\">RA5324</a></td>\r\n");
      out.write("									<td>Jaenab Bajigur</td>\r\n");
      out.write("									<td>Gundam 90' Edition</td>\r\n");
      out.write("									<td><span class=\"badge badge-warning\">Shipping</span></td>\r\n");
      out.write("									<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Detail</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td><a href=\"#\">RA8568</a></td>\r\n");
      out.write("									<td>Rivat Mahesa</td>\r\n");
      out.write("									<td>Oblong T-Shirt</td>\r\n");
      out.write("									<td><span class=\"badge badge-danger\">Pending</span></td>\r\n");
      out.write("									<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Detail</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td><a href=\"#\">RA1453</a></td>\r\n");
      out.write("									<td>Indri Junanda</td>\r\n");
      out.write("									<td>Hat Rounded</td>\r\n");
      out.write("									<td><span class=\"badge badge-info\">Processing</span></td>\r\n");
      out.write("									<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Detail</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td><a href=\"#\">RA1998</a></td>\r\n");
      out.write("									<td>Udin Cilok</td>\r\n");
      out.write("									<td>Baby Powder</td>\r\n");
      out.write("									<td><span class=\"badge badge-success\">Delivered</span></td>\r\n");
      out.write("									<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Detail</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-footer\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Message From Customer-->\r\n");
      out.write("			<div class=\"col-xl-4 col-lg-5 \">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-4 bg-primary d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-light\">Message From\r\n");
      out.write("							Customer</h6>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">Hi there! I am\r\n");
      out.write("									wondering if you can help me with a problem I've been having.</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Udin\r\n");
      out.write("									Cilok · 58m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">But I must\r\n");
      out.write("									explain to you how all this mistaken idea</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time\">Nana Haminah\r\n");
      out.write("									· 58m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">Lorem ipsum dolor\r\n");
      out.write("									sit amet, consectetur adipiscing elit</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Jajang\r\n");
      out.write("									Cincau · 25m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">At vero eos et\r\n");
      out.write("									accusamus et iusto odio dignissimos ducimus qui blanditiis</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Udin\r\n");
      out.write("									Wayang · 54m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-footer text-center\">\r\n");
      out.write("							<a class=\"m-0 small text-primary card-link\" href=\"#\">View\r\n");
      out.write("								More <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--Row-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-12 text-center\">\r\n");
      out.write("				<p>\r\n");
      out.write("					Do you like this template ? you can download from <a\r\n");
      out.write("						href=\"https://github.com/indrijunanda/RuangAdmin\"\r\n");
      out.write("						class=\"btn btn-primary btn-sm\" target=\"_blank\"><i\r\n");
      out.write("						class=\"fab fa-fw fa-github\"></i>&nbsp;GitHub</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal Logout -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("			aria-labelledby=\"exampleModalLabelLogout\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"exampleModalLabelLogout\">Ohh No!</h5>\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<p>Are you sure you want to logout?</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-outline-primary\"\r\n");
      out.write("							data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("						<a href=\"login.html\" class=\"btn btn-primary\">Logout</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!---Container Fluid-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
