/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-05-14 21:29:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1711373671945L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710145615094L));
    _jspx_dependants.put("jar:file:/F:/Project-Java/java-jsp-servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shopgiay-jsp-servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710851876702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Trang chu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid\" id=\"container-wrapper\">\r\n");
      out.write("		<div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("			<h1 class=\"h3 mb-0 text-gray-800\">Thống kê</h1>\r\n");
      out.write("			<ol class=\"breadcrumb\">\r\n");
      out.write("				<li class=\"breadcrumb-item\"><a href=\"./\">Home</a></li>\r\n");
      out.write("				<li class=\"breadcrumb-item active\" aria-current=\"page\">Thống kê</li>\r\n");
      out.write("			</ol>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row mb-3\">\r\n");
      out.write("			<!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Doanh\r\n");
      out.write("									thu (Theo năm)</div>\r\n");
      out.write("								<div class=\"h5 mb-0 font-weight-bold text-gray-800\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${doanhThuTheoNam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\">\r\n");
      out.write("									<span class=\"text-success mr-2\"><i\r\n");
      out.write("										class=\"fa fa-arrow-up\"></i> 0.48%</span> <span>So với năm\r\n");
      out.write("										trước</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-calendar fa-2x text-primary\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Earnings (Annual) Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row no-gutters align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Tổng\r\n");
      out.write("									sản phẩm</div>\r\n");
      out.write("								<div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tongSoLuongGiay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-shopping-cart fa-2x text-success\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- New User Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row no-gutters align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Người\r\n");
      out.write("									dùng</div>\r\n");
      out.write("								<div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tongSoLuongNguoiDung}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\">\r\n");
      out.write("									<span class=\"text-success mr-2\"><i\r\n");
      out.write("										class=\"fas fa-arrow-up\"></i> 1 </span> <span>Người dùng mới</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-users fa-2x text-info\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Pending Requests Card Example -->\r\n");
      out.write("			<div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("				<div class=\"card h-100\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row no-gutters align-items-center\">\r\n");
      out.write("							<div class=\"col mr-2\">\r\n");
      out.write("								<div class=\"text-xs font-weight-bold text-uppercase mb-1\">Yêu\r\n");
      out.write("									cầu được giải quyết</div>\r\n");
      out.write("								<div class=\"h5 mb-0 font-weight-bold text-gray-800\">0</div>\r\n");
      out.write("								<div class=\"mt-2 mb-0 text-muted text-xs\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<i class=\"fas fa-comments fa-2x text-warning\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Area Chart -->\r\n");
      out.write("			<div class=\"col-xl-8 col-lg-7\">\r\n");
      out.write("				<div class=\"card mb-4\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-primary\">Danh thu theo\r\n");
      out.write("							tháng</h6>\r\n");
      out.write("						<!-- <div class=\"dropdown no-arrow\">\r\n");
      out.write("							<a class=\"dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("								id=\"dropdownMenuLink\" data-toggle=\"dropdown\"\r\n");
      out.write("								aria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("								class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("								aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("								<div class=\"dropdown-header\">Dropdown Header:</div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("									class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"chart-area\">\r\n");
      out.write("							<!-- 	<canvas id=\"myAreaChart\"></canvas> -->\r\n");
      out.write("							<canvas id=\"myChart\" width=\"1488\" height=\"640\"\r\n");
      out.write("								style=\"display: block; height: 320px; width: 744px;\"></canvas>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Pie Chart -->\r\n");
      out.write("			<div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("				<div class=\"card mb-4\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-primary\">Bán chạy</h6>\r\n");
      out.write("						<div class=\"dropdown no-arrow\">\r\n");
      out.write("							<a class=\"dropdown-toggle btn btn-primary btn-sm\" href=\"#\"\r\n");
      out.write("								role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\"\r\n");
      out.write("								aria-haspopup=\"true\" aria-expanded=\"false\"> Tháng <i\r\n");
      out.write("								class=\"fas fa-chevron-down\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\r\n");
      out.write("								aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("								<div class=\"dropdown-header\">Chọn</div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\">Tuần</a> <a\r\n");
      out.write("									class=\"dropdown-item\" href=\"#\">Năm</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Nike1\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>20 đến 80 Giày</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-warning\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 80%\" aria-valuenow=\"80\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Nike2\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>20 đến 50 Giày</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-success\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 70%\" aria-valuenow=\"70\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Nike3\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>20 đến 30 Giày</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-danger\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 55%\" aria-valuenow=\"55\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<div class=\"small text-gray-500\">\r\n");
      out.write("								Nike4\r\n");
      out.write("								<div class=\"small float-right\">\r\n");
      out.write("									<b>10 đến 20 Giày</b>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"progress\" style=\"height: 12px;\">\r\n");
      out.write("								<div class=\"progress-bar bg-info\" role=\"progressbar\"\r\n");
      out.write("									style=\"width: 50%\" aria-valuenow=\"50\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-footer text-center\">\r\n");
      out.write("						<a class=\"m-0 small text-primary card-link\" href=\"#\">View More\r\n");
      out.write("							<i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Invoice Example -->\r\n");
      out.write("			<div class=\"col-xl-8 col-lg-7 mb-4\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-primary\">Hóa đơn</h6>\r\n");
      out.write("						<a class=\"m-0 float-right btn btn-danger btn-sm\"\r\n");
      out.write("							href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("'>Xem thêm<i\r\n");
      out.write("							class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table align-items-center table-flush\">\r\n");
      out.write("							<thead class=\"thead-light\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Mã hóa đơn</th>\r\n");
      out.write("									<th>Khách hàng</th>\r\n");
      out.write("									<th>Tổng tiền</th>\r\n");
      out.write("									<th>Trạng thái</th>\r\n");
      out.write("									<th>Hành động</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-footer\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Message From Customer-->\r\n");
      out.write("			<div class=\"col-xl-4 col-lg-5 \">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"card-header py-4 bg-primary d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("						<h6 class=\"m-0 font-weight-bold text-light\">Phản hồi</h6>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">Chào bạn! Tôi là\r\n");
      out.write("									tự hỏi liệu bạn có thể giúp tôi với một vấn đề tôi đang gặp\r\n");
      out.write("									phải không..</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Udin\r\n");
      out.write("									Cilok · 58m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">Chào bạn! Tôi là\r\n");
      out.write("									tự hỏi liệu bạn có thể giúp tôi với một vấn đề tôi đang gặp\r\n");
      out.write("									phải không..</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Udin\r\n");
      out.write("									Cilok · 58m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">Chào bạn! Tôi là\r\n");
      out.write("									tự hỏi liệu bạn có thể giúp tôi với một vấn đề tôi đang gặp\r\n");
      out.write("									phải không..</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Udin\r\n");
      out.write("									Cilok · 58m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"customer-message align-items-center\">\r\n");
      out.write("							<a class=\"font-weight-bold\" href=\"#\">\r\n");
      out.write("								<div class=\"text-truncate message-title\">Chào bạn! Tôi là\r\n");
      out.write("									tự hỏi liệu bạn có thể giúp tôi với một vấn đề tôi đang gặp\r\n");
      out.write("									phải không..</div>\r\n");
      out.write("								<div class=\"small text-gray-500 message-time font-weight-bold\">Udin\r\n");
      out.write("									Cilok · 58m</div>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-footer text-center\">\r\n");
      out.write("							<a class=\"m-0 small text-primary card-link\" href=\"#\">View\r\n");
      out.write("								More <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal Logout -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("			aria-labelledby=\"exampleModalLabelLogout\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"exampleModalLabelLogout\">Ohh No!</h5>\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<p>Are you sure you want to logout?</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-outline-primary\"\r\n");
      out.write("							data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("						<a href=\"/shopbangiay-jsp-servlet/dang-nhap?action=login\"\r\n");
      out.write("							class=\"btn btn-primary\">Logout</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!---Container Fluid-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/admin/home.jsp(225,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/admin-chitiet-hoadon");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/admin/home.jsp(241,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("hoadon");
      // /views/admin/home.jsp(241,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/admin/home.jsp(241,8) '${arr_HoaDon}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${arr_HoaDon}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<tr>\r\n");
            out.write("										<td><a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hoadon.getID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hoadon.getNameAcc()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hoadon.getTongBill()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td><span class=\"badge badge-warning\">Chưa giải\r\n");
            out.write("												quyết</span></td>\r\n");
            out.write("										<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Xem\r\n");
            out.write("												chi tiết</a></td>\r\n");
            out.write("									</tr>\r\n");
            out.write("\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
